apiVersion: v1
kind: Secret
metadata:
  name: keyspaces-credentials
  namespace: spotify-clone
type: Opaque
stringData:
  username: "spotify-app-dev"
  password: "${KEYSPACES_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: spotify-clone
type: Opaque
stringData:
  username: "admin"
  password: "${OPENSEARCH_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: spotify-clone
type: Opaque
stringData:
  username: "admin"
  password: "admin123"  # Change this in production!